apiVersion: v1
kind: Service
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Cambia esto a NodePort si prefieres
