name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: 'latest'

      - name: Log in to ArgoCD
        run: |
          kubectl config set-context minikube --namespace=default
          kubectl config use-context minikube # Reemplaza con el contexto de tu clúster
          kubectl config view
          kubectl config current-context
          kubectl create secret generic argocd-secret --from-literal=server=https://localhost:8080 --from-literal=username=admin --from-literal=password=$ARGO_PASSWORD
          kubectl get secret argocd-secret
        env:
          KUBECONFIG: ${{secrets.KUBE_CONFIG}}
          ARGOCD_PASSWORD: ${{ secrets.ARGO_PASSWORD }}

      - name: Sync Application with ArgoCD
        run: |
          argocd app sync nginx-app --auth-token $ARGO_PASSWORD
        env:
          ARGOCD_OPTS: --insecure
