name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-node-app:latest ./app
          docker tag my-node-app:latest my-node-app:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Publish Docker image to Docker Hub
        run: |
          echo DOCKERHUB_TOKEN  | docker login -u $DOCKER_USERNAME --password-stdin
          docker push my-node-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
