name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: 'latest'

      - name: Log in to ArgoCD
        run: |
          kubectl config set-context minikube
          kubectl config use-context minikube
          kubectl config view
          kubectl config current-context
          argocd login --insecure https://localhost:8080 --username admin --password $ARGO_PASSWORD
          argocd app sync nginx-app
        env:
          KUBECONFIG: ${{secrets.KUBE_CONFIG}}
          ARGOCD_PASSWORD: ${{ secrets.ARGO_PASSWORD }}

      - name: Sync Application with ArgoCD
        run: |
          argocd app sync nginx-app --auth-token $ARGO_PASSWORD
        env:
          ARGOCD_OPTS: --insecure
