name: Deploy Nginx Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          k8s-version: 'latest'

      - name: Configure kubectl
        run: |
          kubectl config set-context minikube --namespace=default --server=https://127.0.0.1:61886
          kubectl config use-context minikube
        env:
          KUBECONFIG: ${{secrets.KUBE_CONFIG}}

      - name: Deploy Nginx Application
        run: |
          helm upgrade --install my-nginx ./chart/my-nginx/chart
        env:
          HELM_CHART_VERSION: '0.1.0' # Cambia esto según la versión de tu Chart
