name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: Azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t yugarcia/desafio_imagen:latest .
          docker push yugarcia/desafio_imagen:latest

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install my-nginx ./charts/my-nginx
